### ISSUE TITLE
build failure with ghc-7.6.0.20120810

### ISSUE THREAD

**Issue by kfish** [thoughtpolice/vacuum#3]
"cabal install vacuum" fails with ghc-7.6.0.20120810 (ghc-7.6.1-rc1):

src/GHC/Vacuum/ClosureType.hs:34:0:
     error: #error Unsupported GHC version in ClosureTypes.hs!

**Comment by thoughtpolice** [comment]
Ah, right. I'll fix this shortly.

**Comment by thoughtpolice** [comment]
Fixed in f3a39a5ed94d835f91fc695a2e9987ef03ae288f
